org: juliabraz
app: slack-jira-bot-app
service: slack-jira-bot

useDotenv: true

package:
  patterns:
    - '!venv/**'
    - '!node_modules/**'
    - '!.pytest_cache/**'
    - '!databases/**'
    - '!docker/**'
    - '!__pycache__/**'
    - '!data/**'
    - '!scripts/**'
    - '!tests/**'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    CLOUD_PROVIDER: AWS
    TICKET_LINKS_TABLE: !Ref TicketLinksTable
    CHANNEL_CONFIGS_TABLE: !Ref ChannelConfigsTable
    AWS_SQS_URL: !Ref BotQueue
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    JIRA_SERVER: ${env:JIRA_SERVER}
    JIRA_EMAIL: ${env:JIRA_EMAIL}
    JIRA_API_TOKEN: ${env:JIRA_API_TOKEN}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            - !GetAtt BotQueue.Arn
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
          Resource:
            - !GetAtt TicketLinksTable.Arn
            - !GetAtt ChannelConfigsTable.Arn

functions:
  api:
    handler: app.api.lambda_handler.lambda_handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

  worker:
    handler: app.workers.lambda_handler.lambda_handler
    events:
      - sqs:
          arn: !GetAtt BotQueue.Arn

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.api.main.app
  pythonRequirements:
    dockerizePip: false

resources:
  Resources:
    BotQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "slack-jira-bot-queue"
        VisibilityTimeout: 60

    TicketLinksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TicketLinks
        AttributeDefinitions:
          - AttributeName: issue_key
            AttributeType: S
        KeySchema:
          - AttributeName: issue_key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ChannelConfigsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ChannelConfigs
        AttributeDefinitions:
          - AttributeName: channel_id
            AttributeType: S
        KeySchema:
          - AttributeName: channel_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
